#ifndef __AUDIO_H__
#define __AUDIO_H__

typedef enum 
{
//---------------------------------------------------
	AUD_BASE_ID_PRO_AUDIO = 1,//按键音

	AUD_BASE_ID_INPUT_68_PWD = 2,//请输入6-8位密码
	AUD_BASE_ID_PWD_68_LEN = 3, //密码应为6-8位
	AUD_BASE_ID_PWD_INPUT_AGAIN = 4,//请再次输入密码
	AUD_BASE_ID_SUCCESS = 5,//操作成功
	AUD_BASE_ID_NOT_SAME = 6,//两次输入不一致
	AUD_BASE_ID_CONTINUE = 7,//继续请按#
	AUD_BASE_ID_FAIL = 8,//操作失败
	AUD_BASE_ID_INPUT_OLD_PWD = 9,//请输入旧密码
	AUD_BASE_ID_PWD_NOT_EXIST = 10,//密码不存在
	AUD_BASE_ID_INPUT_NEW_PWD = 11,//请输入新密码
	AUD_BASE_ID_PWD_SAME = 12,//新旧密码一致
	AUD_BASE_ID_INPUT_DEL_PWD = 13,//请输入要删除的密码
	AUD_BASE_ID_NUM_NOT_EXIST = 14,//编号不存在
	AUD_BASE_ID_INPUT_CONFIRM = 15,//确认请按#
	AUD_BASE_ID_PRESS_FP = 16,//请按手指
	AUD_BASE_ID_PRESS_FP_AGAIN = 17,//请再按一次
	AUD_BASE_ID_FP_SAME = 18,//新旧指纹一致
	AUD_BASE_ID_PRESS_OLD_FP = 19,//请按旧的指纹
	AUD_BASE_ID_PRESS_NEW_FP = 20,//请按新的指纹
	AUD_BASE_ID_INPUT_DEL_FP = 21,//请输入要删除的指纹
	AUD_BASE_ID_FP_NOT_EXIST = 22,//指纹不存在
	AUD_BASE_ID_PRESS_RFCARD = 23,//请刷卡
	AUD_BASE_ID_PRESS_RFCARD_AGAIN = 24,//请再刷一次
	AUD_BASE_ID_RFCARD_EXIST = 25,//RF卡已存在
	AUD_BASE_ID_PRESS_OLD_RFCARD = 26,//请刷旧卡
	AUD_BASE_ID_PRESS_NEW_RFCARD = 27,//请刷新卡
	AUD_BASE_ID_RFCARD_SAME = 28,//新旧RF卡一致
	AUD_BASE_ID_INPUT_DEL_RFCARD = 29,//请输入要删除的RF卡
	AUD_BASE_ID_RFCARD_NOT_EXIST = 30,//RF卡不存在
	AUD_BASE_ID_PWD_EXIST = 31,//密码已存在
	AUD_BASE_ID_INPUT_ADMIN_PWD = 32,//请输入管理员密码
	AUD_BASE_ID_SET_SUCESS = 33,//设置成功
	AUD_BASE_ID_SET_FAIL = 34,//设置失败
	AUD_BASE_ID_INPUT_END = 35,//按#键结束
	AUD_BASE_ID_RETRY = 36,//请重试
	AUD_BASE_ID_INPUT_BACK = 37,//返回按*
	AUD_BASE_ID_CONTACT_ADMIN = 38,//请联系管理员
	AUD_BASE_ID_REINPUT = 39,//请重新输入
	AUD_BASE_ID_ADD_ADMIN_PWD_FIRST = 40,//为了您的使用安全，请先添加管理员密码
	AUD_BASE_ID_DOOR_OPEN = 41,//已开锁
	AUD_BASE_ID_DOOR_CLOSE = 42,//已关锁
	AUD_BASE_ID_PWD_WRONG = 43,//密码错误
	AUD_BASE_ID_FP_WRONG = 44,//指纹错误
	AUD_BASE_ID_RFCARD_WRONG = 45,//RF卡错误
	AUD_BASE_ID_RONG_TIMES_EXCEED = 46,//错误次数已超限制，请稍后重试
	AUD_BASE_ID_LOW_BATTERY = 47,//电量低

	AUD_BASE_ID_SYS_PASSWORD = 48,//密码
	AUD_BASE_ID_SYS_FP = 49,//指纹
	AUD_BASE_ID_SYS_RFCARD = 50,//RF卡
	AUD_BASE_ID_SYS_ADMIN = 51,//管理员
	AUD_BASE_ID_SYS_SETTING = 52,//设置
	AUD_BASE_ID_SYS_RESTORE = 53,//恢复出厂设置
	AUD_BASE_ID_SYS_ADD_PWD = 54,//添加密码
	AUD_BASE_ID_SYS_CHG_PWD = 55,//修改密码
	AUD_BASE_ID_SYS_DEL_PWD = 56,//删除密码
	AUD_BASE_ID_SYS_CLR_PWD = 57,//删除所有密码
	AUD_BASE_ID_SYS_ADD_FP = 58,//添加指纹
	AUD_BASE_ID_SYS_CHG_FP = 59,//修改指纹
	AUD_BASE_ID_SYS_DEL_FP = 60,//删除指纹
	AUD_BASE_ID_SYS_CLR_FP = 61,//删除所有指纹
	AUD_BASE_ID_SYS_ADD_RFCARD = 62,//添加RF卡
	AUD_BASE_ID_SYS_CHG_RFCARD = 63,//修改RF卡
	AUD_BASE_ID_SYS_DEL_RFCARD = 64,//删除RF卡
	AUD_BASE_ID_SYS_CLR_RFCARD = 65,//删除所有RF卡
	AUD_BASE_ID_SYS_CHG_ADMIN_PWD = 66,//修改管理员密码
	AUD_BASE_ID_SYS_CHG_ADMIN_FP = 67,//修改管理员指纹
	AUD_BASE_ID_SYS_NO1_ADMIN_FP = 68,//1号管理员指纹
	AUD_BASE_ID_SYS_NO2_ADMIN_FP = 69,//2号管理员指纹
	AUD_BASE_ID_SYS_PRO_AUDIO = 70,//提示音
	AUD_BASE_ID_SYS_CLOSE_PRO_AUDIO = 71,//关闭
	AUD_BASE_ID_SYS_OPEN_PRO_AUDIO = 72,//开启
	AUD_BASE_ID_SYS_OPEN_MODE = 73,//开门方式
	AUD_BASE_ID_SYS_SIN_OPEN_MODE = 74,//单开门方式
	AUD_BASE_ID_SYS_DBL_OPEN_MODE = 75,//双开门方式
	AUD_BASE_ID_SYS_RESTORE_SUCCESS = 76,//初始化成功
	AUD_BASE_ID_APP_SYN = 77,//请使用app同步
	AUD_BASE_ID_FM_KEY_INPUT = 78,//请测试所有按键
	AUD_BASE_ID_FM_RESTORE = 79,//请按复位键
	AUD_BASE_ID_SYS_NUM_0 = 80,//0
	AUD_BASE_ID_SYS_NUM_1 = 81,//1
	AUD_BASE_ID_SYS_NUM_2 = 82,//2
	AUD_BASE_ID_SYS_NUM_3 = 83,//3
	AUD_BASE_ID_SYS_NUM_4 = 84,//4
	AUD_BASE_ID_SYS_NUM_5 = 85,//5
	AUD_BASE_ID_SYS_NUM_6 = 86,//6
	AUD_BASE_ID_SYS_NUM_7 = 87,//7
	AUD_BASE_ID_SYS_NUM_8 = 88,//8
	AUD_BASE_ID_SYS_NUM_9 = 89,//9
	AUD_BASE_ID_SYS_NUM_S = 90,//*
	AUD_BASE_ID_SYS_NUM_H = 91,//#
	AUD_BASE_ID_MEM_FULL = 92,//操作失败，锁内储存空间已满

	AUD_BASE_ID_MAX,

}AUD_PLAY_ID;


void Audio_Init(void);

void Audio_Play(AUD_PLAY_ID aud_id);

void Audio_Stop(void);

#endif
